### PR TITLE
Add sort event

### LINKED ISSUE #6: Respond to sort event?
It would be nice if the element order could be kept in sync with the order of sorted Ampersand collections (collections with comparators). Thoughts?

### PR DESCRIPTION
**Pull request by CodyWalker**
Listen for `sort` events on collections. Closes #6.

### CODE REVIEW

**Comment by oneforwonder** [comment]
@lukekarrys @HenrikJoreteg Following up on this... 

I think this is a valuable change that should be merged.

The Travis CI build failure seems to have nothing to do with the content of this PR. (Maybe there is bitrot with CI process?)

Either I think the very small change in this PR can be seen to be bug-free.

**Comment by markwoon** [comment]
Any progress on this?  Would love to see this merged.

Quoting @wraithgar in  #77:

> Tests ran from PRs from external repos will always fail, only tests made from PRs from local branches will run.

**Comment by dhritzkiv** [comment]
Sorry to keep this PR unattended for so long. This does indeed seem like a small -but useful- commit with no foreseeable side-effects. Unfortunately there's no tests to double check, but I will merge and release anyway.

**Comment by dhritzkiv** [comment]
Published as v1.1.0. v2.0.0 is also available and features lodash@v4 as a dependency

**Pull request merged**
