### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by nadavspi**
componenet -> component

### CODE REVIEW

**Comment by wraithgar** [comment]
@AmpersandJS/core-team who has access to this repo? npm?

**Comment by fyockm** [comment]
Looks like @HenrikJoreteg is the only npm maintainer. Not sure about this repo - probs the same.

**Comment by HenrikJoreteg** [comment]
gah! fixed: https://www.npmjs.com/package/ampersand-react-mixin/access

**Comment by wraithgar** [comment]
@HenrikJoreteg ok how about this repo?

**Comment by HenrikJoreteg** [comment]
@wraithgar @fyockm yup, yup, sorry.

**Comment by HenrikJoreteg** [comment]
@wraithgar @fyockm what i meant to also say was, that should be fixed now #facepalm

**Comment by lukekarrys** [comment]
Published as `v0.1.2`

**Pull request merged**
